### ISSUE TITLE
train_inpainting.py

### ISSUE THREAD

**Issue by Xiao0219** [ewrfcas/PGIC_inpainting#13]
![image](https://github.com/user-attachments/assets/0ea006e3-91ab-42a8-8a85-3a847c1534f0)
![image](https://github.com/user-attachments/assets/45267f10-3ceb-42f6-9891-95b10463e365)

Hello, Happy National Day. Sorry to bother you during the holiday. I encountered a problem when running the training code: I checked and it seems to be a val_image_path problem. I don’t seem to find this path in the configuration file you gave, and megadepth_overlap.py did not generate this file. Can you tell me how to solve it?

**Comment by ewrfcas** [comment]
Thanks for this problem. We will handle this quickly.

**Comment by ewrfcas** [comment]
We are uploading these pairs to https://huggingface.co/datasets/ewrfcas/LeftRefill/tree/main. It would contain 2 zip files with about 1GB at all.
